--DROP TABLE IF EXISTS users;
--DROP TABLE IF EXISTS requests;
--DROP TABLE IF EXISTS items;
--DROP TABLE IF EXISTS bookings;
--DROP TABLE IF EXISTS comments;

--CREATE SCHEMA IF NOT EXISTS shareit;

CREATE TABLE IF NOT EXISTS  users
(
    id     BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)     NOT NULL,
    email       VARCHAR(100)     NOT NULL    UNIQUE
);

CREATE TABLE IF NOT EXISTS requests
(
    id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description     VARCHAR(200)    NOT NULL,
    requester_id    BIGINT          REFERENCES users(id) ON DELETE CASCADE,
    created         TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS items
(
    id     BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)    NOT NULL,
    description VARCHAR(200)    NOT NULL,
    owner_id    BIGINT          REFERENCES users(id) ON DELETE CASCADE,
    available   BOOLEAN,
    request_id  BIGINT          REFERENCES requests(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    id   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date  TIMESTAMP WITHOUT TIME ZONE     NOT NULL,
    end_date    TIMESTAMP WITHOUT TIME ZONE     NOT NULL,
    item_id     BIGINT          REFERENCES items(id) ON DELETE CASCADE,
    booker_id   BIGINT          REFERENCES users(id) ON DELETE CASCADE,
    status      VARCHAR(20)     NOT NULL        DEFAULT 'WAITING'
);

CREATE TABLE IF NOT EXISTS comments
(
    id  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text        VARCHAR(300)    NOT NULL,
    item_id     BIGINT          REFERENCES items(id) ON DELETE CASCADE,
    author_id   BIGINT          REFERENCES users(id) ON DELETE CASCADE,
    created     TIMEStAMP WITHOUT TIME ZONE
);